In [1]:
import numpy as np
import pandas as pd
import calendar
from datetime import datetime

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# Loading data
data = pd.read_csv('sales.csv')

# Converting the Datetime datatype  to datetime
data['OrderDate'] = pd.to_datetime(data['OrderDate'])

# creating new columns(hour,date,weekday,month)
data['date'] = data['OrderDate'].dt.date
data["weekday"] = data['OrderDate'].dt.strftime('%A')
data["month"] = data['OrderDate'].dt.month_name()
data['year'] = data['OrderDate'].dt.year

# Categorical boolean mask
categorical_feature_mask = data.dtypes==object

#filter categorical columns using mask and turn it into a list

categorical_cols = data.columns[categorical_feature_mask].tolist()

# Although date is an object, it is been added when converting datetime to datetime obejct. so let us remove that from list.
categorical_cols.remove('date')
categorical_cols.remove("Total")
print(categorical_cols)

['Region', 'Rep', 'Item', 'weekday', 'month']

In [3]:
# need to install category_encoders first by this below command
!pip install --upgrade category_encoders

Requirement already up-to-date: category_encoders in c:\users\abhilash\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied, skipping upgrade: pandas>=0.21.1 in c:\users\abhilash\anaconda3\lib\site-packages (from category_encoders) (1.1.4)
Requirement already satisfied, skipping upgrade: scikit-learn>=0.20.0 in c:\users\abhilash\anaconda3\lib\site-packages (from category_encoders) (0.23.2)
Requirement already satisfied, skipping upgrade: scipy>=1.0.0 in c:\users\abhilash\anaconda3\lib\site-packages (from category_encoders) (1.4.1)
Requirement already satisfied, skipping upgrade: numpy>=1.14.0 in c:\users\abhilash\anaconda3\lib\site-packages (from category_encoders) (1.18.1)
Requirement already satisfied, skipping upgrade: patsy>=0.5.1 in c:\users\abhilash\anaconda3\lib\site-packages (from category_encoders) (0.5.1)
Requirement already satisfied, skipping upgrade: statsmodels>=0.9.0 in c:\users\abhilash\anaconda3\lib\site-packages (from category_encoders) (0.11.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in c:\users\abhilash\anaconda3\lib\site-packages (from pandas>=0.21.1->category_encoders) (2.8.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in c:\users\abhilash\anaconda3\lib\site-packages (from pandas>=0.21.1->category_encoders) (2019.3)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in c:\users\abhilash\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (0.14.1)
Requirement already satisfied, skipping upgrade: threadpoolctl>=2.0.0 in c:\users\abhilash\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (2.1.0)
Requirement already satisfied, skipping upgrade: six in c:\users\abhilash\anaconda3\lib\site-packages (from patsy>=0.5.1->category_encoders) (1.14.0)

In [4]:
from sklearn.preprocessing import OneHotEncoder
import category_encoders as ce

In [8]:
ohe = ce.OneHotEncoder(handle_unknown='ignore', use_cat_names=False)
X_train_ohe = ohe.fit_transform(data[categorical_cols])
X_train_ohe.head()

C:\Users\ABHILASH\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

,Region_1,Region_2,Region_3,Rep_1,Rep_2,Rep_3,Rep_4,Rep_5,Rep_6,Rep_7,...,month_3,month_4,month_5,month_6,month_7,month_8,month_9,month_10,month_11,month_12
0,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0